// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Model;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(ProductsContext))]
    [Migration("20241218124501_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApi.Model.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Price = 1000m,
                            ProductName = "Iphone 13",
                            Status = true
                        },
                        new
                        {
                            ProductId = 2,
                            Price = 1001m,
                            ProductName = "Iphone 14",
                            Status = true
                        },
                        new
                        {
                            ProductId = 3,
                            Price = 1111m,
                            ProductName = "Iphone 15",
                            Status = true
                        },
                        new
                        {
                            ProductId = 4,
                            Price = 1222m,
                            ProductName = "Iphone 16",
                            Status = false
                        },
                        new
                        {
                            ProductId = 5,
                            Price = 2000m,
                            ProductName = "Iphone 17",
                            Status = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
